name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps: 
    - name: Set GitHub main branch
      run: git config --global init.defaultBranch main

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: ./tournament-app
      run: npm ci --legacy-peer-deps

    - name: Build and deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: www.grumble.cc
        working-directory: ./tournament-app
        env:
          token: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID }}

