name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps: 
    - name: Set GitHub name
      run: git config --global user.name "${GITHUB_ACTOR}"
      
    - name: Set GitHub email
      run: git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: ./tournament-app
      run: npm ci --legacy-peer-deps

    - name: Build and deploy
      working-directory: ./tournament-app
      run: npm run deploy
      env:
        token: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID }}

    - name: Create CNAME
      run: echo "www.grumble.cc" > CNAME

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'CNAME' # Or the pattern of files to add
        message: 'Add CNAME via GitHub Actions'
        branch: 'deploy' # The target branch for the commit

